### ISSUE TITLE
Example App Not working?

### ISSUE THREAD

**Issue by DavidAwad** [watson-developer-cloud/visual-recognition-nodejs#1]
I've cloned the app with my own Watson credentials and It's unfortunately not working. 

I keep getting the error :

```
Error processing the request. Please try again.
``` 

The JS console is telling me the server is throwing a 500 error. 
I've gotten  the same error on local and on the web app. 2013 MacBook Air.

**Comment by germanattanasio** [comment]
It's working for me.

Did you replace `url`, `username` and `password`?

```js
var credentials = extend({
  url: '<url>',
  username: '<username>',
  password: '<password>'
}, bluemix.getServiceCreds('visual_recognition')); // VCAP_SERVICES
```

**Comment by jsstylos** [comment]
This is a common issue -- we should catch it in the wrapper and provide a more useful error message.

**Comment by germanattanasio** [comment]
The app is not using the wrapper.

**Comment by jsstylos** [comment]
We should fix that too :-)

**Comment by germanattanasio** [comment]
Hi @DavidAwad, we have an npm module that you can use to call the services: 
[npmjs.com/package/watson-developer-cloud](npmjs.com/package/watson-developer-cloud)

**Comment by germanattanasio** [comment]
@jsstylos The wrapper doesn't required the `url` and if the credentials are wrong it will say:

```js
{
 code: 401,
 error: 'Unauthorized: Access is denied due to invalid credentials'
}
```
I agree we need to update this sample, I will open create a task for that
