### ISSUE TITLE
Deploy failing

### ISSUE THREAD

**Issue by whiskeyneon** [watson-developer-cloud/visual-recognition-nodejs#134]
I have tried master and the latest beta release, but both are failing to deploy on Bluemix.
This is a screenshot of the error on the application
![screenshot from 2016-06-13 10-07-48](https://cloud.githubusercontent.com/assets/7538988/16016229/baa63642-314e-11e6-9500-9628a0d2f1c2.png)
This is the log showing the only error. It's unfortunate that there isn't any reason why there is an error so I could try figuring this out on my own.
![screenshot from 2016-06-13 10-08-43](https://cloud.githubusercontent.com/assets/7538988/16016495/2c16cef8-3150-11e6-983e-0022afb7a948.png)

**Comment by germanattanasio** [comment]
did you update the API_KEY environment variable?

**Comment by whiskeyneon** [comment]
That was the issue, thank you! I followed the documentation on the readme file, but changing the API key was not included in the instructions for running it on Bluemix.
