### ISSUE TITLE
Visual Recognition Service is not added when the project is deployed on Bluemix

### ISSUE THREAD

**Issue by leandrodvd** [watson-developer-cloud/visual-recognition-nodejs#181]
When I use the "Deploy on Bluemix" option,  the visual recognition service is not added/bind. I think it should be declared in manifest.yml

**Comment by germanattanasio** [comment]
This was fixed.
![screen shot 2016-07-28 at 5 48 53 pm](https://cloud.githubusercontent.com/assets/313157/17230673/9b723ecc-54eb-11e6-8dc0-fdbdc73cf5a9.png)


App: http://visual-recognition-nodejs-germanattanasio-1716.eu-gb.mybluemix.net/
