### ISSUE TITLE
Custom Classifier not getting picked up

### ISSUE THREAD

**Issue by swamichandra** [watson-developer-cloud/visual-recognition-nodejs#183]
After training a custom classifier successfully, it is not getting picked up. Getting "No matching classifiers found." message.

**Comment by kognate** [comment]
Can you paste the response you got on the creation step?

**Comment by swamichandra** [comment]
Not sure which response you are looking for. But here is the info about the custom classifier model.

swamchan$ curl -X GET "https://gateway-a.watsonplatform.net/visual-recognition/api/v3/classifiers/PackageIdentifier_1887047378?api_key=xxxxxx&version=2016-05-20"
{
    "classifier_id": "PackageIdentifier_1887047378",
    "name": "PackageIdentifier",
    "owner": "xx-xx-xx-xx-xxx",
    "status": "ready",
    "created": "2016-07-01T02:27:25.809Z",
    "classes": [{"class": "PackageFound"}]
}

**Comment by germanattanasio** [comment]
@swamichandra is this a demo issue or a question about the API?

**Comment by swamichandra** [comment]
The issue is about the demo. I trained a new classifier and pointed the
demo app to use the API key. But the new classifier is not getting used and
the app seems to be reverting back to the default VR models.

**Comment by kognate** [comment]
There is no way to use a classifier in the demo app unless it was trained in the demo app.    You would have to modify the demo app quite a bit because the demo app expects the trained classifiers to be deleted soon.

**Comment by swamichandra** [comment]
That's a bummer. What would it take to specify a particular classifier ID to be used by the app? I'm not able to locate where in the app the classifier ID is specified even for the default model.

**Comment by germanattanasio** [comment]
The classifier id is being saved in a cookie call `classifier`

**Comment by germanattanasio** [comment]
I've created and issue to prevent people from opening issues and asking for where things are in the code #185
