### ISSUE TITLE
VR V3 AlchemyAPI

### ISSUE THREAD

**Issue by hayslan1** [watson-developer-cloud/visual-recognition-nodejs#184]
Hi everybody . Is it still necessary in Visual Recognition V3 to use the Alchemy API and then set the environments variables in manual mode as fig. attached.
<img width="1440" alt="cfa96906-f684-11e5-9b2e-233753333f79" src="https://cloud.githubusercontent.com/assets/17702862/16568948/c8ba5e16-4206-11e6-8ba6-300f63f2d1d7.png">

**Comment by germanattanasio** [comment]
You don't need an alchemy key to use Visual recognition v3 and the environment variables you have are probably from an old version of the app.
