### ISSUE TITLE
Write instructions on how to update the bundles and use your own classifier.

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/visual-recognition-nodejs#185]
The README should have a section describing how to add/remove/update bundles. It should also list the steps to manually set a classifier and prevent the demo from deleting it.

**Comment by kognate** [comment]
Should the app itself have an easy way to get this (like a link to click and show the classifier id?  or maybe an env var that prevents classifier deletion)?

**Comment by germanattanasio** [comment]
make sense.
