### ISSUE TITLE
VR V3 don't deploy.

### ISSUE THREAD

**Issue by hayslan1** [watson-developer-cloud/visual-recognition-nodejs#190]
Visual Recognition don't deploy on my Bluemix. Generates error on the final of the process when was trying to upload something.

**Comment by kognate** [comment]
What errors is it generating?  It would be best if you could paste in the commands you ran and the output it generated.  

Thanks.

**Comment by hayslan1** [comment]
I will generate the error again and send you. Thanks.

**Comment by hayslan1** [comment]
Follows attached complete log of the deploy.

[log_bluemix.txt](https://github.com/watson-developer-cloud/visual-recognition-nodejs/files/360332/log_bluemix.txt)

**Comment by hayslan1** [comment]
Then Pittsburgh... Some idea?

**Comment by kognate** [comment]
I don't have any idea yet.  I can't deploy it as a normal user either.  @germanattanasio 

I'm still investigating.

**Comment by nfriedly** [comment]
Did you try doing `cf logs visual-recognition-nodejs-visrecmor-1848 --recent` afterwards? Any useful info there?

**Comment by hayslan1** [comment]
I will check.

**Comment by kognate** [comment]
I just ran that,  it looks like it's a problem with babelify


 Error: Cannot find module 'babelify' from '/home/vcap/app'

**Comment by kognate** [comment]
I think I've got it sorted.  PR in process.

**Comment by kognate** [comment]
Ok,  I know what the problem is but the easy fix isn't going to work.  

Here is the workaround: 

checkout commit `476bce622b2e204ec20d5967b5e57613dda15367` and
use that commit.

```
$ git checkout 476bce622b2e204ec20d5967b5e57613dda15367
HEAD is now at 476bce6... Updates the README to describe common uses
$ cf push
```

and that will get you running with the demo for now.  I'm going to fix the other issue, which is a problem with too much disk space being used by some of the node modules.  

Thank you.

**Comment by hayslan1** [comment]
You are the man Pittsburgh. It's working perfectly.
