### ISSUE TITLE
Unable to Load .zip file for Classifier

### ISSUE THREAD

**Issue by Emballanco** [watson-developer-cloud/visual-recognition-nodejs#219]
I am trying to train Visual Recognition by loading zip files. When I attempt to load I receive an error message "You can only upload zipped archives of images". See the image in the attached file.
![visual recognition error](https://cloud.githubusercontent.com/assets/18618255/17942708/7e41fb8c-6a06-11e6-95e7-69d4fe688466.JPG)

I tried Winzip and Windows Explorer file compression. A representative zip file is attached.
[Bridges.zip](https://github.com/watson-developer-cloud/visual-recognition-nodejs/files/435413/Bridges.zip)

I experience the same problem on the Visual Recognition demo site.

**Comment by kognate** [comment]
Thanks.  I think I can see the problem.  For now,  if you could try to select the box and pick the file out of the file picker you should avoid that error.

**Comment by Emballanco** [comment]
Joshua,

I’m afraid I received the error (with zipped spelled correctly) after applying the changes.

Ed

Edward M Ballanco
EMB Information Technologies Inc.
757-810-1751
Edward.ballanco@embinfotech.com<mailto:Edward.ballanco@embinfotech.com>
Visit our web site http://www.embinfotech.com/

**Comment by kognate** [comment]
Can you go to this URL and paste in what is says about your browser please?

https://www.whatismybrowser.com/detect/what-is-my-user-agent

**Comment by Emballanco** [comment]
Here it is:

What is my User Agent?
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
This page shows you what your web browser is sending in the "User-Agent" header for your HTTP requests.

Ed

Edward M Ballanco
EMB Information Technologies Inc.
757-810-1751
Edward.ballanco@embinfotech.com<mailto:Edward.ballanco@embinfotech.com>
Visit our web site http://www.embinfotech.com/

**Comment by kognate** [comment]
Thanks.   We are looking into this.
