### ISSUE TITLE
can't retrain on the free plan

### ISSUE THREAD

**Issue by ACLM** [watson-developer-cloud/visual-recognition-nodejs#227]
{ [Error: Cannot retrain a classifier under the free plan. ]
  code: 400,
  error: 'Cannot retrain a classifier under the free plan. ' } [ 'classifier_id', 'beagle_positive_examples' ] null

**Comment by germanattanasio** [comment]
That's working as intended @ACLM. The API doesn't let you retrain classifiers if you are using a free tier.
