### ISSUE TITLE
zip files lead to 404 error

### ISSUE THREAD

**Issue by QueD** [watson-developer-cloud/visual-recognition-nodejs#243]
I was trying to download the 2 zip files towards the end and got 404 errors for both of them. Please update or send me the new links for the both of them

**Comment by germanattanasio** [comment]
Which zip files? This demo has some bundles that you can use so if you are talking about them you can easily navigate the files and download them.

For example: https://github.com/watson-developer-cloud/visual-recognition-nodejs/blob/master/public/images/bundles/dogs/beagle.zip

**Comment by QueD** [comment]
The zip files towards the end that you use to train the data to recognize the fruit bowls. They lead to 404 errors when you click on them. Can you please update them.

**Comment by germanattanasio** [comment]
@QueD I just fixed the links. Check in the instructions for the new links

**Comment by QueD** [comment]
Thank you very much, German. Away from my computer at the moment but will check it asap.

**Comment by QueD** [comment]
I just checked, and when I try to upload them it says "you can only upload Zipped archives of images." Also, the page says to "Select or drag a zipped folder with at least 50 images." I looked in the zip folders and they dont contain that many. Do you have any with more, and that will upload? thanks

**Comment by germanattanasio** [comment]
Yes. All the Bundles in https://github.com/watson-developer-cloud/visual-recognition-nodejs/blob/master/public/images/bundles/ can be used to train a classifier

**Comment by QueD** [comment]
How can I download the fruit folder as a zip from the link you sent? And also, where can I find the negative training set data for the fruit? I know you fixed the links, but as I noted the upload would not accept that.
