### ISSUE TITLE
File upload seems broken

### ISSUE THREAD

**Issue by QueD** [watson-developer-cloud/visual-recognition-nodejs#244]
It seems this issue was never resolved as I am facing the same thing: 
https://github.com/watson-developer-cloud/visual-recognition-nodejs/issues/219

I have attached an image of the error

![err](https://cloud.githubusercontent.com/assets/4538672/22181160/a2dbacf4-e053-11e6-817f-61cd314d19cb.JPG)

**Comment by germanattanasio** [comment]
What's the zip file you are trying to use?

**Comment by QueD** [comment]
The two you updated the links with yesterday, and I added some JPEGs
from the bundle you linked with more fruit photos.

Want me to upload them? Not on my PC now but can later.
On 01/22/2017 at 12:08 PM, "German Attanasio"  wrote:

	What's the zip file you are trying to use?

**Comment by germanattanasio** [comment]
@KSlachta can you look at this?

**Comment by KSlachta** [comment]
Yea I'll see what I can do

**Comment by ehdsouza** [comment]
@KSlachta any update on this issue?

**Comment by KSlachta** [comment]
Do you have the zip files used so I can look at them?

**Comment by germanattanasio** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
