### ISSUE TITLE
security.js - for VR Nodejs Rate limiting to API is set too low at 10 should be higher.

### ISSUE THREAD

**Issue by Jeffl-at-ibm** [watson-developer-cloud/visual-recognition-nodejs#255]
A customer using the VR Nodejs demo was getting 429 errors after uploading more than 10 images. 
this number is set too low for most customer demos and evaluations and should be set to a higher number to reduce the occurrence of hitting 429 errors.

**Comment by germanattanasio** [comment]
10 images every 30 seconds seems like a good rate limitation for a service demo. The customer can always download the code and create it's own service instance and that won't have the rate limitation
