### ISSUE TITLE
Argument error

### ISSUE THREAD

**Issue by longbowtech** [watson-developer-cloud/visual-recognition-nodejs#264]
Hi, i followed the steps provided. but i hit this error when run it on cmd.

![capture](https://user-images.githubusercontent.com/33303777/32309926-d268291a-bfc9-11e7-8b86-df7e30c67a30.PNG)

**Comment by germanattanasio** [comment]
Are you specifying the `api_key` in the `.env` file?

**Comment by germanattanasio** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
