### ISSUE TITLE
visualRecognition. detectFaces method doesn't recognise key locally

### ISSUE THREAD

**Issue by piotrekkmt** [watson-developer-cloud/visual-recognition-nodejs#277]
According to the visualRecognition documentation there is a method called detectFaces which takes in similar parameters as the .classify() method.

```js
const fs = require('fs'),
    VisualRecognitionV3 = require('watson-developer-cloud/visual-recognition/v3'),
    visualRecognition = new VisualRecognitionV3({
        api_key: '[MY_REAL_API_KEY]',
        version: '2016-05-20'
    });

const params = {
  images_file: fs.createReadStream('./peter.jpg')
};

visualRecognition.detectFaces(params, (err, res) => {
  if (err) {
    console.log(err);
  } else {
    console.log(JSON.stringify(res, null, 2));
  }
});
```

The classify works good when I send over a picture and returns JSON alright, when I try to use the .detectFaces() with the same parameters I get an error:

```
~/Git/watson-developer-cloud  node watsonImageRecognition.js 
{
  "status": "ERROR",
  "statusInfo": "invalid-api-key-permissions"
}
```

Am I missing something in the parameters to run this **locally**? 
I tried exporting in the environment variable **VISUAL_RECOGNITION_API_KEY=[MY_REAL_API_KEY]** 
but that did nothing also. It works fine with classify() just the detectFaces does nothing and asks for the API_KEY... any thoughts?

**Comment by piotrekkmt** [comment]
Ok, after a bit of investigation I think the problem is not with the module code but with the api route the module is calling. A CURL to the same url does not recognise the the api_key parameter in the call. This may be a problem with the route itself then

**Comment by KSlachta** [comment]
Hi Peter, are you having any trouble with this demo in particular or are you just having a problem with the visual recognition node SDK? If you are not having any issues with this Visual Recognition demo please post your issue here https://github.com/watson-developer-cloud/node-sdk. Thank you!

**Comment by peterpoliwoda** [comment]
Hey Kyle, turns out the API was not playing ball when I testing my app. The facial-recognition route was just not taking in the API_Key, but it looks like it has been sorted out and now it's returning some fine JSON results. Thanks for reaching out.
