### ISSUE TITLE
Add GDPR Language to Stand Alone Demo Pages

### ISSUE THREAD

**Issue by mamoonraja** [watson-developer-cloud/visual-recognition-nodejs#279]
**Context:**
GDPR will go into effect on May 25th; we need the demos to display the following language in order to make them compliant with the law:

`This system is for demonstration purposes only and is not intended to process Personal Data. No Personal Data is to be entered into this system as it may not have the necessary controls in place to meet the requirements of the General Data Protection Regulation (EU) 2016/679.`

For more information see: https://github.ibm.com/Watson/developer-experience/issues/4342

**How to update:**
If you are using `watson-react-components` for your demo, you need to update the description in `Jumbotron`.

**Comment by KSlachta** [comment]
Has been added:

![screen shot 2018-04-23 at 3 55 27 pm](https://user-images.githubusercontent.com/26226920/39149961-cda3c34a-470e-11e8-95b9-969cebe2c6b6.png)
