### ISSUE TITLE
We are working to get Visual Recognition up and running shortly!

### ISSUE THREAD

**Issue by surmar49** [watson-developer-cloud/visual-recognition-nodejs#281]
Hi,
I downloaded the source code and added the api key in the .env file and run "npm install" and "npm start". When I try to select an image the following message appears "We are working to get Visual Recognition up and running shortly!". I tried to upload an image but the same message appears. Anything I am missing here?

![image](https://user-images.githubusercontent.com/8286623/42431676-9be42092-8364-11e8-8319-408e7a9b493d.png)

Thanks
Suresh

**Comment by germanattanasio** [comment]
@surmar49 can you try again? I made some updates to the app so it should work correctly now
