### ISSUE TITLE
Cannot read property 'fields' of undefined

### ISSUE THREAD

**Issue by cybertron611** [watson-developer-cloud/visual-recognition-nodejs#283]
<img width="855" alt="error" src="https://user-images.githubusercontent.com/38643076/43353992-40757d80-9261-11e8-9dc4-73fa5046ba76.png">

why i am facing this issue?

**Comment by germanattanasio** [comment]
Looks like the library we use for file uploads is not defined. did you remove files from the same?

**Comment by TFGT** [comment]
Нет


пн, 30 июля 2018, 14:24 German Attanasio <notifications@github.com>:
