### ISSUE TITLE
how to display only class and score in html?

### ISSUE THREAD

**Issue by cybertron611** [watson-developer-cloud/visual-recognition-nodejs#284]
<img width="960" alt="help" src="https://user-images.githubusercontent.com/38643076/43410265-ee60e446-9443-11e8-98de-2ad47c86e707.png">

i want to display only class and score with that image instead of this.....

**Comment by germanattanasio** [comment]
![giphy](https://user-images.githubusercontent.com/313157/43420075-752c8c58-944b-11e8-9384-8c2ec1215226.gif)

**Comment by cybertron611** [comment]
this is a json format i want to display only class and score of json on html page in table format

**Comment by germanattanasio** [comment]
@cybertron611 I think you are looking for a code snippet in which case I recommend you to look in StackOverflow or https://developer.ibm.com/answers/topics/watson/
