### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by kathrynmcelroy** [watson-developer-cloud/visual-recognition-nodejs#50]
The link on the Train Tab to learn more about classifiers does not work. When clicked, it says "Javascript:void(0);"
<img width="774" alt="screen shot 2016-02-16 at 10 58 33 am" src="https://cloud.githubusercontent.com/assets/5400092/13083876/7c17366a-d49c-11e5-93a0-8bce3a2f6e4d.png">

<img width="624" alt="screen shot 2016-02-16 at 10 59 24 am" src="https://cloud.githubusercontent.com/assets/5400092/13083874/78eae7d4-d49c-11e5-90b9-be533cb3bc8c.png">

The proper link is this one: http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/doc/visual-recognition/overview.shtml

**Comment by nfriedly** [comment]
Thanks @kathrynmcelroy! I've got it fixed in the code, we'll update the app shortly.
