### ISSUE TITLE
Watson Vis Rec doesn't work 

### ISSUE THREAD

**Issue by hayslan1** [watson-developer-cloud/visual-recognition-nodejs#58]
Hi. I am developing or trying to develop an app with Watson Visual Recognition scripts available on GitHub but that doesn't work on the Blue Mix environment. Follows attached prints. Someone saw something similar. I did all the manual's steps. Thanks in advance.

![bluemix1](https://cloud.githubusercontent.com/assets/17702862/13746817/ef04e7ac-e9d3-11e5-87e0-945ea7e5eda4.jpg)
![bluemix2](https://cloud.githubusercontent.com/assets/17702862/13746818/ef064ef8-e9d3-11e5-925e-1828d22384f4.jpg)
![bluemix3](https://cloud.githubusercontent.com/assets/17702862/13746816/eeff1e12-e9d3-11e5-92e1-1a0c4f9da9ac.jpg)

**Comment by jzhang300** [comment]
@hayslan1 
Try the Deploy to Bluemix Button on the README:
[![Deploy to Bluemix](https://bluemix.net/deploy/button.png)](https://bluemix.net/deploy?repository=https://github.com/watson-developer-cloud/visual-recognition-nodejs)

This works for me, see if it works for you.

**Comment by hayslan1** [comment]
Thank you James. This really work.
