### ISSUE TITLE
Image URL doesn't work

### ISSUE THREAD

**Issue by kathrynmcelroy** [watson-developer-cloud/visual-recognition-nodejs#63]
The "Paste image URL here" box does not deliver results.

Both on the "Try it" tab and the "Test" tab.

**Comment by jzhang300** [comment]
Some url's do not work because the servers they're hosted on don't allow them to be used in apps like ours.

**Comment by kathrynmcelroy** [comment]
Then we need to give an indication that the URL did not work. Right now it doesn't look like the system is even processing or trying the URL

**Comment by kathrynmcelroy** [comment]
Have you found a URL that does actually work?

**Comment by jzhang300** [comment]
The change is staged and working, but hasn't been promoted to the main app yet.
