### ISSUE TITLE
Visual Recognition Demo Doesn't work 

### ISSUE THREAD

**Issue by hayslan1** [watson-developer-cloud/visual-recognition-nodejs#71]
Hello everybody. What is going on with the Visual Recognition Demo? I had a old version and was working well... Now stop!!!

![print](https://cloud.githubusercontent.com/assets/17702862/14122482/6989423e-f5d2-11e5-8907-0f9fa38e96e4.jpg)

**Comment by jzhang300** [comment]
What's the issue you're running into?

**Comment by hayslan1** [comment]
Hallo James. Is that... When I run the app then apear the message as the print attached. Says "The demo is not available right now . We are working on getting this back up and running soon". And I am  in new cloud, under registration of the company where I Work.

**Comment by hayslan1** [comment]
See... The account that I was testing is working still the demo. Probably the code was updated.

**Comment by jzhang300** [comment]
Does the message appear when you just start the app, or does it appear when you input an image?

**Comment by hayslan1** [comment]
After input the image James.

**Comment by jzhang300** [comment]
if you open this in Google Chrome, can you open the "Developer Tools," hit the "Network Tab," and then input the image again?  I want to know what error is returned.

**Comment by hayslan1** [comment]
Hallo James. So sorry the lateness... We are in different time zone but follows the print of the network tab at developer tools when I am inputting the image and generates the error. 
![print3](https://cloud.githubusercontent.com/assets/17702862/14140118/7fded302-f64d-11e5-9d6b-cde2eb15e975.jpg)

**Comment by jzhang300** [comment]
Can you click on "Body" tab?

**Comment by hayslan1** [comment]
1 {"code":400,"error":"invalid-api-key"}

**Comment by jzhang300** [comment]
Ok, looks like you will need to provide the API Key for Alchemy Vision

**Comment by hayslan1** [comment]
Yes... I see. But shouldn't be it automatic? As the previously deployment. The difference is... The cloud that a did test before was on the evaluation time and the cloud of this test is registered already.

**Comment by jzhang300** [comment]
It's not automatic, you will need to bind the [Alchemy service](https://console.ng.bluemix.net/catalog/services/alchemyapi/) to the app on Bluemix as well.

To run this locally, you can create a `.env.js` file that looks like this in the root directory of the project:
```js
module.exports = {
  VCAP_SERVICES: JSON.stringify({
    visual_recognition: [{
      credentials: {
        "password": "<your visual recognition password>",
        "url": "https://gateway.watsonplatform.net/visual-recognition-beta/api",
        "username": "<your visual recognition username>"
      }
    }]
  }),
  VCAP_APP_PORT: 3000,
  ALCHEMY_KEY: "<your Alchemy API key from Bluemix tile>"
};
```

**Comment by hayslan1** [comment]
Hmm.. No problem. To bind that on the environment is easy. I hope that works. :-)

**Comment by jzhang300** [comment]
:+1: Best of luck @hayslan1 :)

**Comment by hayslan1** [comment]
Ops James. I found another problem. First when I try to bind my app with the service, my service is not on the list. Second when I try to open my service, then apear a error as follows on the image.
![print4](https://cloud.githubusercontent.com/assets/17702862/14148173/dd2c0e22-f674-11e5-97d8-042e5e5fc060.jpg)

**Comment by jzhang300** [comment]
I don't know what that page is about but just click on "Service Credentials" for credentials.

**Comment by hayslan1** [comment]
That's my dashboard. When I click to see the details of my service it's generates the previously error.
![print5](https://cloud.githubusercontent.com/assets/17702862/14149228/8d2fb6da-f679-11e5-886b-3e5d827757df.jpg)

**Comment by hayslan1** [comment]
Ok. I did create a new service and rebind to the app. The error keep. I think that this cloud has some kind of problem. :-(

**Comment by jzhang300** [comment]
I think that error is fine, it's just some iFrame.  Have you tried clicking "service credentials" tab when you click on a service?

**Comment by hayslan1** [comment]
The credentials I can see as below. I only omit for post the information of User and pass.


{
  "visual_recognition": [
    {
      "name": "Visual Recognition-pl",
      "label": "visual_recognition",
      "plan": "free",
      "credentials": {
        "url": "https://gateway.watsonplatform.net/visual-recognition-beta/api",
        "password": "XXXXXXXXXXXXXXXXX",
        "username": "XXXXXXXXXXXXXXXXX"
      }
    }
  ]
}

**Comment by hayslan1** [comment]
Well James. I redeploy the Visual Recognition project and keep the same error, all are duty tied as the print bellow and with credentials. Today we lost a precious opportunity to show for the bosses here on the company, how wonderful the Watson technology is. 
![print6](https://cloud.githubusercontent.com/assets/17702862/14151286/9a401036-f683-11e5-8f89-f40b707e34ed.jpg)

**Comment by jzhang300** [comment]
Looks like Visual Recognition is working, now you need to bind [Alchemy API](https://console.ng.bluemix.net/catalog/services/alchemyapi/) to your app

**Comment by hayslan1** [comment]
I added the Alchemy API tie with the App and keep don't recognizing the credentials. Generates the same error.
![print7](https://cloud.githubusercontent.com/assets/17702862/14154515/21bf7ab0-f693-11e5-98be-4c5de353ca00.jpg)

**Comment by jzhang300** [comment]
Go to "Environment Variables" -> "User-defined" tab and try adding a line for "ALCHEMY_KEY"
<img width="1440" alt="screen shot 2016-03-30 at 2 39 26 pm" src="https://cloud.githubusercontent.com/assets/1449523/14154912/cfa96906-f684-11e5-9b2e-233753333f79.png">

**Comment by hayslan1** [comment]
Wow. Great James... That's working. You are the man.

**Comment by jzhang300** [comment]
B-)
