### ISSUE TITLE
Update the readme to use the new service

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/visual-recognition-nodejs#88]

**Comment by PhilippeComte** [comment]
Hello German, Yes the readme is not yet adapted to the new combined service. Not only the name but the fact that it uses an api key and no longer a Username + password. Thanks

**Comment by nfriedly** [comment]
BTW, I just updated the node SDK to support pulling VR v3 credentials from environment properties in v1.9.3.

**Comment by germanattanasio** [comment]
I've updated the README with instructions for creating a new service instance.
