### ISSUE TITLE
URL regular expression is overly restrictive

### ISSUE THREAD

**Issue by jsstylos** [watson-developer-cloud/visual-recognition-nodejs#90]
Should allow ":"s in urls, like https://commons.wikimedia.org/wiki/File:OIC_street_sign_south_perth_old.jpg

**Comment by kognate** [comment]
This seems to be because the imageExists function in use.js:228 is calling the error callback for that url.

**Comment by kognate** [comment]
Upon further investigation,  the url supplied is not an image url.  It's a web page url.  For example, if you use https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/OIC_street_sign_south_perth_old.jpg/320px-OIC_street_sign_south_perth_old.jpg

it works just fine.
