### ISSUE TITLE
Extreme aspect ratios don't display well

### ISSUE THREAD

**Issue by jsstylos** [watson-developer-cloud/visual-recognition-nodejs#91]
For example: http://myinwood.net/wp-content/uploads/2008/11/academy-street-resized.jpg displays cropped in the demo response.

**Comment by jzhang300** [comment]
yeah now would be pretty good case for image preview

**Comment by jzhang300** [comment]
btw, @jsstylos you should probably move these issues to the working-on-a-saturday repo https://github.ibm.com/watson-developer-cloud/working-on-a-saturday/issues

**Comment by germanattanasio** [comment]
@jzhang300 we are adding `landscape` to the image in this case. Can you check this?

**Comment by jzhang300** [comment]
This is not a simple fix, extreme images are too extreme.

**Comment by jsstylos** [comment]
Is it just a matter of removing the "landscape" tag? That fixed it for this example.

**Comment by jzhang300** [comment]
I'm aware of the landscape tags and all.

The problem is that if it's too extreme, it will be illegible.

I believe the solution to this issue requires more design thought into it, not just a development fix.

**Comment by germanattanasio** [comment]
fixed
